version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://user:password@db/prod_db
      - JWT_SECRET_KEY=your_production_secret_key
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prod_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
